spring:
  datasource:
    url: jdbc:mysql://106.15.186.91:3306/mc-erp-busi?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&connectionTimeZone=Asia/Shanghai
    username: root
    password: '@rootROOT'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      async-init: true # 异步初始化连接
      initial-size: 1 # 初始化时创建的连接数
      min-idle: 5 # 连接池中保持的最小空闲连接数
      max-active: 20 # 连接池中同时可分配的最大连接数
      max-wait: 3000 # 当连接池中没有可用连接时，等待连接被分配的最长时间，单位为毫秒。如果超过这个时间则抛出异常
      time-between-eviction-runs-millis: 60000 # 连接池中的空闲连接验证、清理线程的运行间隔时间，单位为毫秒
      min-evictable-idle-time-millis: 300000 # 连接在池中保持空闲而不被驱逐的最小时间，单位为毫秒
      validation-query: SELECT 1 # 用于验证连接是否有效的 SQL 查询
      validation-query-timeout: 1000 # 用于验证连接的超时时长，单位为毫秒
      test-while-idle: true # 是否在连接空闲时进行连接验证
      test-on-borrow: false # 是否在借用连接时进行连接验证
      test-on-return: false # 是否在归还连接时进行连接验证
      pool-prepared-statements: true # 是否缓存 PreparedStatement，也就是 PSCache
      max-pool-prepared-statement-per-connection-size: 20 # 每个连接上缓存的 PreparedStatement 的最大数目
      connection-error-retry-attempts: 0  # 获取连接失败时的重试次数
      break-after-acquire-failure: true  # 获取连接失败后是否中断
      time-between-connect-error-millis: 30000 # 连接出错后重试时间间隔，单位为毫秒

logging:
  level:
    com:
      alibaba:
        druid: DEBUG

mc:
  erp:
    admin:
      url: "http://localhost:8081/admin/"
